language: node_js
node_js:
  - "11.12.0"
script:
  - echo "Deploying!"
install:
 - npm install -g firebase-tools 
 - yarn install
 - yarn build
after_success:
  - firebase deploy --project kapaltoba --token $FIREBASE_TOKEN